apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tic-tac-toe-bestpractice
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Honeyshah624/argocd_app_deploy.git
    targetRevision: HEAD
    path: charts/tic-tac-toe-chart
    helm:
      releaseName: tic-tac-toe-bestpractice
      valueFiles:
        - ../../clusters/local/tic-tac-toe-values.yml

  destination:
    server: https://kubernetes.default.svc
    namespace: tic-tac-toe-bestpractice

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true